### ISSUE TITLE
pls tell me how to automatically generate this repo from source

### ISSUE THREAD

**Issue by wanghaisheng** [hl7-fhir/hl7-fhir.github.io#2]
I want to convert fhir spec to markdown and use gitbook to tranlate  them to different languages
how can I realize my purpose just like you did here

**Comment by jmandel** [comment]
The FHIR build tool is a Java-based application that outputs the spec website as HTML. So what you're seeing here is actually the output of running the code in [this svn repository](http://gforge.hl7.org/gf/project/fhir/scmsvn/) (also mirrored on github [here](https://github.com/hl7-fhir/fhir-svn)).

Hope this helps!
