### ISSUE TITLE
Stop wiping the git history of the website

### ISSUE THREAD

**Issue by muntact** [hl7-fhir/hl7-fhir.github.io#4]
This repository only has a single commit, which means that other sources are needed to determine the actual difference in the FHIR spec; whereas i should be able to determine it via the git repository.

Please follow a normal git pattern of adding additional commits to an existing repository, rather than force pushing a single commit to master. 

For example the electron github.io page: https://github.com/electron/electron.atom.io/commits/gh-pages

**Comment by jmandel** [comment]
Thanks for the comment! 

Unfortunately our git build is just a mirror of the HL7 FHIR  svn repository, not an authoritative source. The gh-pages branch reflects the output of our  build process, which is on the order of a gigabyte including things like compiled Java jar files; and it's rebuilt several times daily. So it's not quite practical for us to treat the documentation site as a versioned repository. 

That said, we *do* retain history on the source itself.  See https://github.com/hl7-fhir/fhir-svn/commits/master -- which in practice is a very good way to pursue history on the specification content.

**Comment by muntact** [comment]
Thanks @jmandel 

Sorry for the rather flippant comment, it was just rather upsetting to see that the doc site was a single commit, but i did have an inkling that it being generated from another source could be the reason.

Also thanks for the link to the fhir-svn link, i shall do my digging there :)
